services:
  backend:
    container_name: kupi-backend
    env_file: .env
    image: zlnva/kupi-backend-opti:1.0.0
    ports:
      - 4000:3000
    depends_on:
      - postgres
    restart: always
    networks: 
      - internal
  frontend:
    container_name: kupi-frontend
    image: zlnva/kupi-frontend-opti:1.0.0
    ports:
      - 8081:80
    networks: 
      - external

  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks: 
      - internal

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks: 
      - internal
volumes:
  postgres_data:

networks:
  internal:
  external:


