services:
  backend:
    container_name: kupi-backend
    env_file: .env.developer
    build:
      context: backend
      dockerfile: Dockerfile
    image: zlnva/kupi-backend-dev
    ports:
      - 4000:3001
    depends_on:
      - postgres
    restart: always
    networks: 
      - internal
  frontend:
    container_name: kupi-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: zlnva/kupi-frontend-dev
    ports:
      - 8081:80
    networks: 
      - external

  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file: .env.developer
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks: 
      - internal

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks: 
      - internal
volumes:
  postgres_data:

networks:
  internal:
  external:


